"""Markdown report generation, used by the GitHub Action for PR comments."""

from pathlib import Path

from . import metrics as m
from .scanner import ScanResult
from .score import compute

GRADE_EMOJI = {"A": "🟢", "B": "🟢", "C": "🟡", "D": "🟠", "F": "🔴"}


def to_markdown(result: ScanResult) -> str:
    """Render a scan result as a GitHub-flavored markdown report."""
    s = m.summary(result)
    hs = compute(result)
    emoji = GRADE_EMOJI.get(hs.grade, "")

    lines = [
        f"## {emoji} CodeRadar Health Report — Grade **{hs.grade}** ({hs.total}/100)",
        "",
        "| Component | Score |",
        "|---|---|",
        f"| Documentation | {hs.docs}/25 |",
        f"| Tech debt | {hs.debt}/25 |",
        f"| Modularity | {hs.modularity}/25 |",
        f"| Complexity | {hs.complexity}/25 |",
        "",
    ]

    if hs.advice:
        lines.append("**Suggested fixes:**")
        lines += [f"- {a}" for a in hs.advice]
        lines.append("")

    lines += [
        "<details><summary>Language breakdown "
        f"({s['files']} files, {s['lines']:,} lines)</summary>",
        "",
        "| Language | Files | Lines | Code | Comments |",
        "|---|---|---|---|---|",
    ]
    for lang, stat in m.language_stats(result).items():
        lines.append(
            f"| {lang} | {stat['files']} | {stat['lines']:,} "
            f"| {stat['code']:,} | {stat['comments']:,} |"
        )
    lines += ["", "</details>", ""]

    top = m.top_by_lines(result, 5)
    if top:
        lines += [
            "<details><summary>5 largest files</summary>",
            "",
            "| File | Lines |",
            "|---|---|",
        ]
        for f in top:
            try:
                rel = str(Path(f.path).relative_to(result.root)).replace("\\", "/")
            except ValueError:
                rel = f.path
            lines.append(f"| `{rel}` | {f.total_lines:,} |")
        lines += ["", "</details>", ""]

    lines.append(
        "*Generated by [CodeRadar](https://github.com/FaZ07/CodeRadar) — "
        "grade any codebase in one command.*"
    )
    return "\n".join(lines)
